config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "aboutus", to: "home#aboutus"
  get "signup", to: "users#new"
  get "register", to: "hosptals#new"
  get "utable", to: "users#utable"
  get "htable", to: "hosptals#htable"
  get "requesttable", to: "hosptals#requesttable"
  get "aboutus", to: "home#aboutus"
  get "bookslot", to: "users#bookslot"
  get "uprofile", to: "users#uprofile"
  get "certificate", to: "users#certificate"
  

  # get "getcerti", to: "users#show"

  
  get "/grantvac/:id", to: "users#grantvac"
  
  get "/grantvacs/:id", to: "users#grantvacs"
  

  

  get "/bookfree/:id", to: "hosptals#updatefree"
  get "/bookpaid/:id", to: "hosptals#updatepaid"

  get "/fullfilorderfree/:id", to: "hosptals#fullfilorderfree"
  get "/fullfilorderpaid/:id", to: "hosptals#fullfilorderpaid"

  
  get "/minusonefree/:id", to: "hosptals#minusonefree"
  get "/minusonepaid/:id", to: "hosptals#minusonepaid"
  get "/minustenfree/:id", to: "hosptals#minustenfree"
  get "/minustenpaid/:id", to: "hosptals#minustenpaid"


  get "/confirmuser/:username", to: "hosptals#checkuser"

  get "confirm", to: "hosptals#confirm"
  post "checkuser", to: "hosptals#checkuser"
  

  
  
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "adminlogin", to: "sessions1#new"
  post "adminlogin", to: "sessions1#create"
  delete "adminlogout", to: "sessions1#destroy"

  get "sadminlogin", to: "sessions2#new"
  post "sadminlogin", to: "sessions2#create"
  delete "sadminlogout", to: "sessions2#destroy"

  
  resources :users, except: [:new]
  resources :hosptals, except: [:new]
  resources :admins, except: [:new]
  resources :sadmins, except: [:new]
end

app/models/hosptal.rb
class Hosptal < ApplicationRecord
end

app/controllers/hosptals_controller.rb
class HosptalsController < ApplicationController

    
    def htable
        @hosptals = Hosptal.all
    end
    
    def requesttable
        @hosptals = Hosptal.all
    end

    def new
        @hosptal = Hosptal.new
    
    end

    def create
        @hosptal = Hosptal.new(hosptal_params)
        
        if @hosptal.save
          flash[:notice] = "New Hospital Registered Succesfully."
          redirect_to htable_path
        else
          render 'new'
        end
    end

    def updatefree

        @hosptal = Hosptal.find(params[:id])
        @free_vac = @hosptal.free_vac
        @free_vac = @free_vac - 1
        @hosptal.write_attribute(:free_vac, @free_vac)
        @hosptal.save
        redirect_to confirm_path
    end

    def updatepaid
        @hosptal = Hosptal.find(params[:id])
        @paid_vac = @hosptal.paid_vac
        @paid_vac = @paid_vac - 1
        @hosptal.write_attribute(:paid_vac, @paid_vac)
        @hosptal.save
        redirect_to confirm_path
    end


    def fullfilorderfree

        @hosptal = Hosptal.find(params[:id])
        @free_vac = @hosptal.free_vac
        @free_vac = @free_vac + 10
        @hosptal.write_attribute(:free_vac, @free_vac)
        @hosptal.save
        redirect_to requesttable_path
    end


    def fullfilorderpaid
        @hosptal = Hosptal.find(params[:id])
        @paid_vac = @hosptal.paid_vac
        @paid_vac = @paid_vac + 10
        @hosptal.write_attribute(:paid_vac, @paid_vac)
        @hosptal.save
        redirect_to requesttable_path
    end


    def minusonefree
        @hosptal = Hosptal.find(params[:id])
        @free_vac = @hosptal.free_vac
        if @free_vac!=0
            @free_vac = @free_vac - 1
            @hosptal.write_attribute(:free_vac, @free_vac)
        else
            @hosptal.write_attribute(:free_vac, @free_vac)
        end
        @hosptal.save
        redirect_to htable_path
    end

    def minusonepaid
        @hosptal = Hosptal.find(params[:id])
        @paid_vac = @hosptal.paid_vac
        if @paid_vac!=0
            @paid_vac = @paid_vac - 1
            @hosptal.write_attribute(:paid_vac, @paid_vac)
        else
            @hosptal.write_attribute(:paid_vac, @paid_vac)
        end
        @hosptal.save
        redirect_to htable_path
    end

    def minustenfree
        @hosptal = Hosptal.find(params[:id])
        @free_vac = @hosptal.free_vac
        if @free_vac!=0
            @free_vac = @free_vac - 10
            @hosptal.write_attribute(:free_vac, @free_vac)
        else
            @hosptal.write_attribute(:free_vac, @free_vac)
        end
        @hosptal.save
        redirect_to htable_path
    end


    def minustenpaid
        @hosptal = Hosptal.find(params[:id])
        @paid_vac = @hosptal.paid_vac
        if @paid_vac!=0
            @paid_vac = @paid_vac - 10
            @hosptal.write_attribute(:paid_vac, @paid_vac)
        else
            @hosptal.write_attribute(:paid_vac, @paid_vac)
        end
        @hosptal.save
        redirect_to htable_path
    end


   




    def checkuser

        
        
        @value=params[:username]+".com"
        @user = User.where({:email_id=>@value})
        if @user
            @noofva=@user[0].noofvacc + 1
           if @noofva<=2
                User.where(email_id: @value).update_all(noofvacc:@noofva )
               if @noofva==1
                    User.where(email_id: @value).update_all(vaccine_status:"Partially Vaccinated" )
               else  
                User.where(email_id: @value).update_all(vaccine_status:"Vaccinated" )       
              end
           end
        end
       redirect_to uprofile_path
        # @user = User.find_by(username: params[:username])
        #  @countvac = @ckuser.noofvacc
        #  @countvac = @countvac + 1
         #render json:@user.username

        #  @ckuser.write_attribute(:noofvacc, @countvac)
        #  @ckuser.save
        #  redirect_to uprofile_path
        
        
        
        
        # if logged_in?
        #     @countvac = current_user.noofvacc
        #     @countvac = @countvac + 1
        #     current_user.write_attribute(:noofvacc, @countvac)
        #     current_user.save
        # end
        # redirect_to uprofile_path

        # if @countvac==0
        #     @ckuser.write_attribute(:noofvacc, 1)
        # end
        # if @countvac==1
        #     @ckuser.write_attribute(:noofvacc, 2)
        # end
            
        # @ckuser.save

        




        # @countvac = @countvac + 1
        # # @ckuser.update(noofvacc:@countvac)
        # @ckuser.update_attributes(noofvacc: '@countvac')
        
        # @ckuser.save

        
        # render json:@ckuser

    end

    
    



    private
      
    def hosptal_params
        params.require(:hosptal).permit(:hospital_id, :hospital_name, :address, :phone_no, :pin_code, :free_vac, :paid_vac)
    end
    
    



end 

app/views/hosptals/confirm.html.erb
<h1>Conform You Booking</h1>



<%= form_with(scope: :session, url: checkuser_path) do |f| %>
 
<div class="form-group">
  <%= f.label :username %><br/>
  <%= f.text_field :username, class: "form-control" %>
</div>
 

 
<div class="form-group">
  <%if logged_in?%>
    <a href="/confirmuser/<%= current_user.username %>" class="btn btn-primary" role="button" action=f.submit % >Confirm</a>
    <% end %>
</div>


 
<% end %>

app/views/hosptals/htable.html.erb
<p id="notice"><%= notice %></p>

<h1>Hospitals table (Admin access)</h1>


<table class="table table-striped table-bordered table-hower">
  <thead class="thead-dark">
    <tr>
      <th>Hospital ID</th>
      <th>Hospital Name</th>
      <th>Address</th>
      <th>Phone no</th>
      <th>Pin code</th>
      <th>Free Vaccines Available</th>
      <th>Paid Vaccines Available</th>
    
    </tr>
  </thead>

  <tbody>
    <% @hosptals.each do |hosptal| %>
      <tr>
        <td><%= hosptal.hospital_id %></td>
        <td><%= hosptal.hospital_name %></td>
        <td><%= hosptal.address %></td>
        <td><%= hosptal.phone_no %></td>
        <td><%= hosptal.pin_code %></td>
        <td><%= hosptal.free_vac %> &nbsp <a href="/minusonefree/<%= hosptal.id %>" class="btn btn-primary" role="button" % >Minus 1</a> &nbsp <a href="/minustenfree/<%= hosptal.id %>" class="btn btn-primary" role="button" % >Minus 10</a></td>
        <td><%= hosptal.paid_vac %> &nbsp <a href="/minusonepaid/<%= hosptal.id %>" class="btn btn-primary" role="button" % >Minus 1</a> &nbsp <a href="/minustenpaid/<%= hosptal.id %>" class="btn btn-primary" role="button" % >Minus 10</a></td>
        
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/hosptals/new.html.erb
<div class="container">


<h1>New Hopital Registration</h1>

<%= form_with(model: @hosptal, local: true) do |f| %>

 
 
<div class="form-group">
  <%= f.label :HospitalID %><br/>
  <%= f.text_field :hospital_id, class: "form-control" %>
</div>
 

<div class="form-group">
  <%= f.label :hospital_name %><br/>
  <%= f.text_field :hospital_name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :address %><br/>
  <%= f.text_field :address, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :phone_no %><br/>
  <%= f.text_field :phone_no, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :pin_code %><br/>
  <%= f.text_field :pin_code, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :free_vac %><br/>
  <%= f.text_field :free_vac, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :paid_vac %><br/>
  <%= f.text_field :paid_vac, class: "form-control" %>
</div>



  </br>
<div class="form-group">
  
  <button class="btn btn-success" type="submit">Submit</button>
</div>
 
<% end %>


</div>

app/views/hosptals/requesttable.html.erb
<p id="notice"><%= notice %></p>

<h1>Vaccine Order List from Hospitals</h1>


<table class="table table-striped table-bordered table-hower">
  <thead class="thead-dark">
    <tr>
      <th>Hospital ID</th>
      <th>Hospital Name</th>
      <th>Address</th>
      <th>Phone no</th>
      <th>Pin code</th>
      <th>Free Vaccines Available</th>
      <th>Paid Vaccines Available</th>
    
    </tr>
  </thead>

  <tbody>
    <% @hosptals.each do |hosptal| %>
      <tr>
        <% if ( hosptal.free_vac==0 && hosptal.paid_vac==0 ) %>
        <td><%= hosptal.hospital_id %></td>
        <td><%= hosptal.hospital_name %></td>
        <td><%= hosptal.address %></td>
        <td><%= hosptal.phone_no %></td>
        <td><%= hosptal.pin_code %></td>
        <td><%= hosptal.free_vac %> &nbsp &nbsp <a href="/fullfilorderfree/<%= hosptal.id %>" class="btn btn-warning" role="button" % >Grant</a></td>
        <td><%= hosptal.paid_vac %> &nbsp &nbsp <a href="/fullfilorderpaid/<%= hosptal.id %>" class="btn btn-warning" role="button" % >Grant</a></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/hosptals/updatefree.html.erb
<h1>Conform You Booking</h1>



<%= form_with(scope: :session, url: checkuser_path) do |f| %>
 
<div class="form-group">
  <%= f.label :username %><br/>
  <%= f.text_field :username, class: "form-control" %>
</div>
 

 
<div class="form-group">
  <%= f.submit "Confirm", class: "btn btn-primary" %>
</div>
 
<% end %>

app/views/hosptals/updatepaid.html.erb
<h1>Conform You Booking</h1>
<form class="" action="<%= checkuser_path %>" method="post">

    <%= token_tag %>
    <p>
    <label for="">username</label>
    <input type="email" name="username" value="">
    </p>

    <input type="submit" name="Submit" value="Confirm" class="btn">




</form>