config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "aboutus", to: "home#aboutus"
  get "signup", to: "users#new"
  get "register", to: "hosptals#new"
  get "utable", to: "users#utable"
  get "htable", to: "hosptals#htable"
  get "requesttable", to: "hosptals#requesttable"
  get "aboutus", to: "home#aboutus"
  get "bookslot", to: "users#bookslot"
  get "uprofile", to: "users#uprofile"
  get "certificate", to: "users#certificate"
  

  # get "getcerti", to: "users#show"

  
  get "/grantvac/:id", to: "users#grantvac"
  
  get "/grantvacs/:id", to: "users#grantvacs"
  

  

  get "/bookfree/:id", to: "hosptals#updatefree"
  get "/bookpaid/:id", to: "hosptals#updatepaid"

  get "/fullfilorderfree/:id", to: "hosptals#fullfilorderfree"
  get "/fullfilorderpaid/:id", to: "hosptals#fullfilorderpaid"

  
  get "/minusonefree/:id", to: "hosptals#minusonefree"
  get "/minusonepaid/:id", to: "hosptals#minusonepaid"
  get "/minustenfree/:id", to: "hosptals#minustenfree"
  get "/minustenpaid/:id", to: "hosptals#minustenpaid"


  get "/confirmuser/:username", to: "hosptals#checkuser"

  get "confirm", to: "hosptals#confirm"
  post "checkuser", to: "hosptals#checkuser"
  

  
  
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "adminlogin", to: "sessions1#new"
  post "adminlogin", to: "sessions1#create"
  delete "adminlogout", to: "sessions1#destroy"

  get "sadminlogin", to: "sessions2#new"
  post "sadminlogin", to: "sessions2#create"
  delete "sadminlogout", to: "sessions2#destroy"

  
  resources :users, except: [:new]
  resources :hosptals, except: [:new]
  resources :admins, except: [:new]
  resources :sadmins, except: [:new]
end

app/models/user.rb
class User < ApplicationRecord

has_secure_password



# validates :username, presence: true
validates :username, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
validates :password, presence: true
validates :first_name, presence: true
validates :last_name, presence: true
validates :gender, presence: true
validates :vaccine_status, presence: true
validates :aadhaar, presence: true
validates :email_id, presence: true
validates :phone_no, presence: true
validates :address, presence: true
validates :pin_code, presence: true
validates :noofvacc, presence: true
validates :vcount, presence: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def uprofile
    end

    def certificate
    end
    
    
    # def show
    #     respond_to do |format|
    #       format.html
    #       format.pdf do
    #         render pdf: "file_name" , template: "users/uprofile.html.erb"   # Excluding ".pdf" extension.
    #       end
    #     end
    #   end

    def show
        respond_to do |format|
          format.html
          format.pdf do
            pdf = UserPdf.new(@users)
            
            send_data pdf.render, filename: 'certfificate.pdf', type: 'application/pdf', disposition: "inline"
            redirect_to uprofile_path
          end
        end
    end
    
    def utable
        @users = User.all
    end
    
    def new
        @user = User.new
    
    end
# "first_name"
        # t.string "last_name"
        # t.string "gender"
        # t.string "vaccine_status"
        # t.string "aadhaar"
        # t.string "email_id"
        # t.string "phone_no"
        # t.string "address"
        # t.string "pin_code"
    def create
        @user = User.new(user_params)
        # @user=User.new
        # @user.username = params[:username]
        # @user.password = params[:password]
        # @user.first_name = params[:first_name]
        # @user.last_name = params[:last_name]
        # @user.vaccine_status = params[:vaccine_status]
        # @user.aadhaar = params[:aadhaar]
        # @user.email_id = params[:email_id]
        # @user.phone_no = params[:phone_no]
        # @user.address = params[:address]
        # @user.pin_code = params[:pin_code]
        # @user.save
        # @user = User.new(user_params)
        if @user.save
          flash[:notice] = "User created."
          redirect_to login_path
        else
          render 'new'
        end
    end

    def edit
        if !logged_in?
            #redirect to login page
        else 
            #do stuff
        end
       
    
    
    end

    def grantvac
        @user = User.find(params[:id])
        @vaccount = @user.noofvacc
        @vaccount = @vaccount + 1
        
        @user.write_attribute(:noofvacc, @vaccount)
        @user.save
        # render json:@user
        

        redirect_to uprofile_path
    end


    def grantvacs
        @user = User.find(params[:id])
        @vaccount = @user.vcount

        if  @vaccount.eql?("0")
            @user.write_attribute(:vcount, 1)
        end
        if @vaccount.eql?("1")
            @user.write_attribute(:vcount, 2)
        end
            
        
        
        @user.save
        # render json:@user
        

        redirect_to utable_path
    end


    def bookslot
        @hosptals = Hosptal.all
    end

    def bookfree

        
        @user.username =  Hosptal.find_by(id:params[:id])

    end


    def bookpaid
        
    
    
    end


    


      
    
    
    
    private
      
        def user_params
            params.require(:user).permit(:username, :password, :first_name, :last_name, :gender, :vaccine_status, :aadhaar, :email_id, :phone_no, :address, :pin_code, :noofvacc, :vcount)
        end
        
        # "first_name"
        # t.string "last_name"
        # t.string "gender"
        # t.string "vaccine_status"
        # t.string "aadhaar"
        # t.string "email_id"
        # t.string "phone_no"
        # t.string "address"
        # t.string "pin_code"


end

app/views/users/bookslot.html.erb
<p id="notice"><%= notice %></p>

<h1>Book a vaccination Slot</h1>


<table class="table table-striped table-bordered table-hower">
  <thead class="thead-dark">
    <tr>
      <th>Hospital ID</th>
      <th>Hospital Name</th>
      <th>Address</th>
      <th>Phone no</th>
      <th>Pin code</th>
      <th>Free Vaccines Available</th>
      <th>Paid Vaccines Available</th>
    
    </tr>
  </thead>

  <tbody>
    <% @hosptals.each do |hosptal| %>
      <tr>
        <% if ( hosptal.free_vac!=0 || hosptal.paid_vac!=0 ) %>
        <td><%= hosptal.hospital_id %></td>
        <td><%= hosptal.hospital_name %></td>
        <td><%= hosptal.address %></td>
        <td><%= hosptal.phone_no %></td>
        <td><%= hosptal.pin_code %></td>
        <td><%= hosptal.free_vac %> &nbsp &nbsp &nbsp <a href="/bookfree/<%= hosptal.id %>" class="btn btn-warning" role="button" % >Book Slot</a></td>
        <td><%= hosptal.paid_vac %> &nbsp &nbsp &nbsp <a href="/bookpaid/<%= hosptal.id %>" class="btn btn-warning" role="button" % >Book Slot</a></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/certi.html.erb
<h1>User Certificate</h1>


<% if logged_in?%>
    <h2> <%= current_user.username %> is logged in. </h2>
    <h2> <%= current_user.first_name %> </h2>
    <h2> <%= current_user.last_name %> </h2>
    <h2> <%= current_user.gender %> </h2>
    <h2> <%= current_user.vaccine_status %> </h2>
    <h2> <%= current_user.aadhaar %> </h2>
    <h2> <%= current_user.email_id %> </h2>
    <h2> <%= current_user.phone_no %> </h2>
    <h2> <%= current_user.address %> </h2>
    <h2> <%= current_user.pin_code %> </h2>
    <h2> <%= current_user.noofvacc %> </h2>
    <h2> <%= current_user.vcount %> </h2>
   
    
    



    
<% end %>

app/views/users/certificate.html.erb
<div class="container">

    <hr>
    <h1 class="display-4" ><strong>Certificate of Vaccination</strong></h1>
    <hr>


    <% if logged_in?%>

        <div class="jumbotron" >
        <% if current_user.noofvacc==1%>
            <h2 class="display-4"><%= current_user.first_name %> is Partially Vaccinated.</h2>
        <% end %>

        <% if current_user.noofvacc==2%>
            <h2 class="display-4"><%= current_user.first_name %> is Fully Vaccinated.</h2>
        <% end %>

        
        
        <strong>Username:</strong><%= current_user.username %></br>
        <strong>First Name:</strong><%= current_user.first_name %> </br>
            <strong>Last Name:</strong><%= current_user.last_name %> </br>
            <strong>Gender:</strong><%= current_user.gender %> </br>
            <strong>Vaccine Status:</strong><%= current_user.vaccine_status %> </br>
            <strong>Aadhaar ID:</strong>                    <%= current_user.aadhaar %> </br>
            <strong>Email ID: </strong>                     <%= current_user.email_id %> </br>
            <strong>Phone Number: </strong>                 <%= current_user.phone_no %> </br>
            <strong>Current Address:</strong>               <%= current_user.address %> </br>
            <strong>Pin Code:</strong>                      <%= current_user.pin_code %> </br>
            <strong>Number of Vaccine Doses Taken:</strong> <%= current_user.noofvacc %> </br>
                                
        
        </div>
    
    <% end %>






</div>

app/views/users/new.html.erb
<div class="container">


<h1>Sign Up</h1>

<%= form_with model: @user, local: true do |f| %>
 
<div class="form-group">
  <%= f.label :username %><br/>
  <%= f.email_field :username, class: "form-control" %>
</div>
 
<div class="form-group">
  <%= f.label :password %><br/>
  <%= f.password_field :password, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :first_name %><br/>
  <%= f.text_field :first_name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :last_name %><br/>
  <%= f.text_field :last_name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :gender %><br/>
  <%= f.text_field :gender, class: "form-control" %>
</div>


<div class="form-group">
  
  <%= f.text_field :vaccine_status, class: "form-control", value: "Not Vaccinated", type:"hidden"%>
</div>
<div class="form-group">
  <%= f.label :aadhaar %><br/>
  <%= f.text_field :aadhaar, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :email_id %><br/>
  <%= f.text_field :email_id, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :phone_no %><br/>
  <%= f.text_field :phone_no, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :address %><br/>
  <%= f.text_field :address, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :pin_code %><br/>
  <%= f.text_field :pin_code, class: "form-control" %>
</div>

<div class="form-group">
  
  <%= f.text_field :noofvacc, class: "form-control", value: 0, type:"hidden"%>
</div>

<div class="form-group">
  
  <%= f.text_field :vcount, class: "form-control" , value: "0", type:"hidden"%>
</div>


 </br>
<div class="form-group">
  
  <button class="btn btn-success" type="submit">Submit</button>
</div>
 
<% end %>

</div>

app/views/users/show.html.erb
<h1>show</h1>

app/views/users/uprofile.html.erb
<div class="container">


<h1 class="display-4" ><strong>User Profile</strong></h1>


<% if logged_in?%>

<div class="jumbotron" >
  <h1 class="display-4">Hello, <%= current_user.first_name %></h1>
  <p class="lead">Your Details entered during registration are listed here and same will be printed on the final certifiacte.</p>
  <hr class="my-4">
  <strong>Username:</strong><%= current_user.username %></br>
   <strong>First Name:</strong><%= current_user.first_name %> </br>
    <strong>Last Name:</strong><%= current_user.last_name %> </br>
    <strong>Gender:</strong><%= current_user.gender %> </br>
    <strong>Vaccine Status:</strong><%= current_user.vaccine_status %> </br>
    <strong>Aadhaar ID:</strong>                    <%= current_user.aadhaar %> </br>
    <strong>Email ID: </strong>                     <%= current_user.email_id %> </br>
    <strong>Phone Number: </strong>                 <%= current_user.phone_no %> </br>
    <strong>Current Address:</strong>               <%= current_user.address %> </br>
    <strong>Pin Code:</strong>                      <%= current_user.pin_code %> </br>
    <strong>Number of Vaccine Doses Taken:</strong> <%= current_user.noofvacc %> </br>
                           
  
</div>



    
    
    <%= link_to 'Download Certificate', certificate_path, class:"btn btn-danger", role:"button"%>
    
    



    
<% end %>






</div>

app/views/users/utable.html.erb
<p id="notice"><%= notice %></p>

<h1>Users table (Admin access) </h1>


<table class="table table-striped table-bordered table-hower">
  <thead class="thead-dark">
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Vaccine status</th>
      <th>Aadhaar</th>
      <th>Email ID</th>
      <th>Phone no</th>
      <th>Address</th>
      <th>Pin code</th>
      <th>VaccineTaken</th>
      
      
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.gender %></td>
        <td><%= user.vaccine_status %></td>
        <td><%= user.aadhaar %></td>
        <td><%= user.email_id %></td>
        <td><%= user.phone_no %></td>
        <td><%= user.address %></td>
        <td><%= user.pin_code %></td>
        <td><%= user.noofvacc %></td>
        
        
      </tr>
    <% end %>
  </tbody>
</table>