config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "aboutus", to: "home#aboutus"
  get "signup", to: "users#new"
  get "register", to: "hosptals#new"
  get "utable", to: "users#utable"
  get "htable", to: "hosptals#htable"
  get "requesttable", to: "hosptals#requesttable"
  get "aboutus", to: "home#aboutus"
  get "bookslot", to: "users#bookslot"
  get "uprofile", to: "users#uprofile"
  get "certificate", to: "users#certificate"
  

  # get "getcerti", to: "users#show"

  
  get "/grantvac/:id", to: "users#grantvac"
  
  get "/grantvacs/:id", to: "users#grantvacs"
  

  

  get "/bookfree/:id", to: "hosptals#updatefree"
  get "/bookpaid/:id", to: "hosptals#updatepaid"

  get "/fullfilorderfree/:id", to: "hosptals#fullfilorderfree"
  get "/fullfilorderpaid/:id", to: "hosptals#fullfilorderpaid"

  
  get "/minusonefree/:id", to: "hosptals#minusonefree"
  get "/minusonepaid/:id", to: "hosptals#minusonepaid"
  get "/minustenfree/:id", to: "hosptals#minustenfree"
  get "/minustenpaid/:id", to: "hosptals#minustenpaid"


  get "/confirmuser/:username", to: "hosptals#checkuser"

  get "confirm", to: "hosptals#confirm"
  post "checkuser", to: "hosptals#checkuser"
  

  
  
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "adminlogin", to: "sessions1#new"
  post "adminlogin", to: "sessions1#create"
  delete "adminlogout", to: "sessions1#destroy"

  get "sadminlogin", to: "sessions2#new"
  post "sadminlogin", to: "sessions2#create"
  delete "sadminlogout", to: "sessions2#destroy"

  
  resources :users, except: [:new]
  resources :hosptals, except: [:new]
  resources :admins, except: [:new]
  resources :sadmins, except: [:new]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def aboutus
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to root_path do %>
        <img src="/assets/logo.png" alt="" width="30" height="30" class="d-inline-block align-text-top">
    <% end %>
    <%= link_to 'CoVac', root_path, class:"navbar-brand navbar-"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          
          <%= link_to 'About Us', aboutus_path, class:"nav-link"%>
        </li>
       <% if !logged_in1? && !logged_in? && !logged_in2? %>
            <li class="nav-item">
                <%= link_to 'New User Registration', signup_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to ' User LogIn', login_path, class:"nav-link"%>
            </li>
        <% end %>

        <% if logged_in?  && !logged_in1? && !logged_in2?%>
            <% if current_user.noofvacc<2 %>
            <li class="nav-item">
                <%= link_to "Book Vaccine Slot", bookslot_path, class:"nav-link"%>
            </li>
            <% end %>

            <li class="nav-item">
                <%= link_to "User Profile", uprofile_path, class:"nav-link"%>
            </li>
            
            
            <li class="nav-item">
                <%= link_to "User LogOut", logout_path, method: :delete , class:"nav-link"%>
            </li>
        <% end %>

        
    </ul>

      <ul class="nav navbar-nav navbar-right">
            
        
        
        
        <% if !logged_in? && !logged_in1? && !logged_in2?%>
            <li class="nav-item">
                
                <%= link_to 'Admin Login', adminlogin_path, class:"nav-link"%>
            </li>

        <% end %>

        <% if  logged_in1? && !logged_in? && !logged_in2?%>
            <li class="nav-item">
                <%= link_to 'User Table', utable_path, class:"nav-link"%>
            </li>

            <li class="nav-item">
                <%= link_to 'Hospital table', htable_path, class:"nav-link"%>
            </li>

            <li class="nav-item">
                <%= link_to 'New Hospital Registration', register_path, class:"nav-link"%>
            </li>

            <li class="nav-item">
            <%= link_to "admin Log out", adminlogout_path, method: :delete , class:"nav-link"%>
            </li>

            
        <% end %>

        



        
        
        
        <% if !logged_in? && !logged_in1? && !logged_in2?%>
            <li class="nav-item">
                
                <%= link_to 'State Agency LogIn', sadminlogin_path, class:"nav-link"%>
            </li>

        <% end %>
            
        <% if  logged_in2? && !logged_in? && !logged_in1? %>
            <li class="nav-item">
            <%= link_to "Sadmin Log out", sadminlogout_path, method: :delete , class:"nav-link"%>
            </li>

            <li class="nav-item">
            <%= link_to "Request table", requesttable_path, class:"nav-link"%>
            </li>
        <% end %>
        

        

            
      
      
      
        </ul>
      
    </div>
  </div>
</nav>

app/views/home/aboutus.html.erb
<h1>About us</h1>

<p>We at CoVac.inc worked hard for bringing million of smiles on millions of faces and continuously fighting against covid-19.</p>

<a href="https://twitter.com/MoHFW_INDIA"  ><img src="/assets/twitterlogo.png" alt="" width="40" height="40" class="d-inline-block align-text-top"></a> &nbsp Connect with us on Twitter.
</br></br>
<a href="https://www.facebook.com/MoHFWIndia"  ><img src="/assets/facebooklogo.png" alt="" width="40" height="40" class="d-inline-block align-text-top"></a> &nbsp Connect with us on Facebook.

app/views/home/index.html.erb
</br>

<marquee behavior="rotate" direction="left" BGCOLOR=white><h1>Welcome to CoVac, An Online Vaccination Tracking Portal.</h1></marquee>
</br>



<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="4" aria-label="Slide 5"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="5" aria-label="Slide 6"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="6" aria-label="Slide 7"></button>
    
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/assets/one.png" width= "270px" height="500px" class="d-block w-100" alt="One slide">
      <div class="carousel-caption d-none d-md-block">
        <h5>Take the right step, get vaccinated.</h5>
        <p>Registraions are now open for vaccination, click the links above. </p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="/assets/two.png" width= "270px" height="500px" class="d-block w-100" alt="Two slide" >
      <div class="carousel-caption d-none d-md-block">
        <h5>Take the right step, get vaccinated.</h5>
        <p>Registraions are now open for vaccination, click the links above. </p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="/assets/three.png" width= "270px" height="500px" class="d-block w-100" alt="Three slide">
      <div class="carousel-caption d-none d-md-block">
        <h5>Take the right step, get vaccinated.</h5>
        <p>Registraions are now open for vaccination, click the links above. </p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="/assets/threepointfive.png" width= "270px" height="500px" class="d-block w-100" alt="Four slide">
      <div class="carousel-caption d-none d-md-block">
        <h5>Take the right step, get vaccinated.</h5>
        <p>Registraions are now open for vaccination, click the links above. </p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="/assets/four.png" width= "270px" height="500px" class="d-block w-100" alt="Four slide">
      <div class="carousel-caption d-none d-md-block">
        <h5>Take the right step, get vaccinated.</h5>
        <p>Registraions are now open for vaccination, click the links above. </p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="/assets/five.png" width= "270px" height="500px" class="d-block w-100" alt="Five slide">
      <div class="carousel-caption d-none d-md-block">
        <h5>Take the right step, get vaccinated.</h5>
        <p>Registraions are now open for vaccination, click the links above. </p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="/assets/six.png" width= "270px" height="500px" class="d-block w-100" alt="Six slide">
      <div class="carousel-caption d-none d-md-block">
        <h5>Take the right step, get vaccinated.</h5>
        <p>Registraions are now open for vaccination, click the links above. </p>
      </div>
    </div>
    

  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>

<p>May everyone be healthy and free from illness
India’s Journey of Administering
100 Crore Vaccine Doses</p>
<p>The journey of administering 100 crore ‘Made in India’ vaccines - Covaxin and Covishield - to the citizens of India started on 16th January 2021 under the leadership of Hon’ble Prime Minister Shri Narendra Modi.</p>

<p>Since the dawn of the pandemic, India has shown its commitment to protect its citizens by taking on this arduous and formidable task involving enormous resources, unstinted support of the States/UTs, untiring efforts of Health Care Workers, Front Line Workers and proactive participation of all stakeholders.</p>

<p>100 crore vaccine doses is an unprecedented accomplishment, and the world applauds India.</p>
<p>At MyGov we applaud and celebrate the determination of the Indian citizen, towards overcoming this pandemic.</p>

<p>सर्वे भवन्तु सुखिनः सर्वेसन्तु निरामया।</p>
<p>सर्वे भद्राणि पश्यन्तु मा कश्चिद् दुख भागभवेत।।</p>



</div>